name: CI
on: push

jobs:
  build:
    name: Build
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: Check Python install
        run: |
          which python
          python --version
          python -c "import struct; print(struct.calcsize('P') * 8)"
          which pip
          pip --version

      - name: Install Python dependencies
        run: |
          python -m pip install -U pip setuptools wheel
          python -m pip install -U cachetools pefile

      - name: Build
        run: |
          python setup.py bdist_wheel --python-tag cp37 --plat-name win_amd64

      - name: Prepare for test
        run: |
          dir dist
          Get-ChildItem dist -File | Foreach-Object {$wheelname = $_.Name}
          echo $wheelname
          echo "WHEELNAME=$wheelname" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          $ver = (findstr __version__ .\py2exe\__init__.py).split("'")[1]
          echo $ver
          echo "VER=$ver" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Install
        run: |
          pip install dist\${{ env.WHEELNAME }}
          python -c "import py2exe"

      - name: Test
        run: |
          cd tests
          python maketest.py
          cd functional
          .\runner.bat bundlefiles2_test
          .\runner.bat bundlefiles1_test
          .\runner.bat bundlefiles0_test
          .\runner.bat bundlefiles0_sqlite_test
          .\runner.bat bundlefiles0_ssl_test
          .\runner.bat numpy_test
          .\runner.bat pandas_test
          .\runner.bat pycryptodome_test
          .\runner.bat tk_test
          .\runner.bat sqlite_test
          .\runner.bat certifi_test
          .\runner.bat certifi_zip_test
          .\runner.bat pywin32_test
          .\runner.bat requests_test
          .\runner.bat zope_interface_test
          .\runner.bat ssl_test

      - name: Deploy
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.WHEELNAME }}
          path: |
            dist/${{ env.WHEELNAME }}
