name: CI
on: push

jobs:
  build:
    name: Build
    runs-on: windows-2019
    strategy:
      matrix:
       include:
         - python-version: '3.7'
           python-arch: 'x64'
           python-tag: 'cp37'
           plat-name: 'win_amd64'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.python-arch }}

      - name: Check Python install
        run: |
          which python
          python --version
          python -c "import struct; print(struct.calcsize('P') * 8)"
          which pip
          pip --version

      - name: Install Python dependencies
        run: |
          python -m pip install -U pip setuptools wheel
          python -m pip install -U cachetools pefile

      - name: Build
        run: |
          python setup.py bdist_wheel --python-tag ${{ matrix.python-tag }} --plat-name ${{ matrix.plat-name }}

      - name: Prepare for deployment
        run: |
          dir dist
          $ver = (findstr __version__ .\py2exe\__init__.py).split("'")[1]
          echo $ver
          echo "VER=$ver" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          $wheelname = "py2exe-$ver-${{ matrix.python-tag }}-none-${{ matrix.plat-name }}.whl"
          echo $wheelname
          echo "WHEELNAME=$wheelname" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Deploy
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.WHEELNAME }}
          path: |
            dist/${{ env.WHEELNAME }}

  test:
    needs: build
    name: Test
    runs-on: windows-2019
    strategy:
      matrix:
       include:
         - python-version: '3.7'
           python-arch: 'x64'
           python-tag: 'cp37'
           plat-name: 'win_amd64'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.python-arch }}

      - name: Prepare for test
        run: |
          $ver = (findstr __version__ .\py2exe\__init__.py).split("'")[1]
          echo $ver
          echo "VER=$ver" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          $wheelname = "py2exe-$ver-${{ matrix.python-tag }}-none-${{ matrix.plat-name }}.whl"
          echo $wheelname
          echo "WHEELNAME=$wheelname" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.WHEELNAME }}

      - name: Install
        run: |
          dir
          dir ${{ env.WHEELNAME }}
          pip install ${{ env.WHEELNAME }}
          python -c "import py2exe"

      - name: Test
        run: |
          cd tests
          python maketest.py
          cd functional
          .\runner.bat bundlefiles2_test
          .\runner.bat bundlefiles1_test
          .\runner.bat bundlefiles0_test
          .\runner.bat bundlefiles0_sqlite_test
          .\runner.bat bundlefiles0_ssl_test
          .\runner.bat numpy_test
          .\runner.bat pandas_test
          .\runner.bat pycryptodome_test
          .\runner.bat tk_test
          .\runner.bat sqlite_test
          .\runner.bat certifi_test
          .\runner.bat certifi_zip_test
          .\runner.bat pywin32_test
          .\runner.bat requests_test
          .\runner.bat zope_interface_test
          .\runner.bat ssl_test
